export const ROOT_HELP = [
  "PromptHub CLI",
  "",
  "用于直接读写 PromptHub 本地数据库与技能仓库。默认输出 JSON；如需更易读的输出可加 `--output table`。",
  "",
  "用法:",
  "  prompthub [global options] <resource> <command> [args]",
  "",
  "资源:",
  "  prompt    管理 prompts（含 relation / output-format）",
  "  folder    管理 folders",
  "  agent     管理 Agent 平台、可见性与资产路径",
  "  rules     管理 rules",
  "  workspace 管理工作区导入导出",
  "  skill     管理 skills",
  "  mcp       管理 MCP servers",
  "  plugin    管理 Plugins",
  "  sync      同步自部署或云端工作区",
  "  ai        管理 AI providers、models 和模型路由",
  "  doctor    诊断和恢复本地运行状态",
  "",
  "全局参数:",
  "  --data-dir <dir>        指定 PromptHub userData 目录",
  "  --app-data-dir <dir>    指定 appData 根目录（读取 data-path.json 时使用）",
  "  --output, -o <format>   输出格式：json | table，默认 json",
  "  --summary              返回有界摘要（默认）",
  "  --full                 返回完整资源内容",
  "  --quiet                成功时不输出 stdout，错误仍输出 stderr",
  "  --version, -v           显示 CLI 版本",
  "  --help, -h              显示帮助",
  "",
  "示例:",
  "  prompthub prompt list",
  "  prompthub --output table prompt search design --tags ui,landing",
  '  prompthub prompt create --title "Landing Hero" --user-prompt-file ./prompt.md',
  "  prompthub rules list",
  "  prompthub agent list --filter installed",
  "  prompthub skill import ~/.claude/skills/my-skill",
  "  prompthub skill delete my-skill --purge-managed-repo",
  "  prompthub mcp create --name local-docs --command npx --args -y,@modelcontextprotocol/server-filesystem",
  "  prompthub plugin list",
  "  prompthub ai provider-add --provider openai --api-key $OPENAI_API_KEY --api-url https://api.openai.com/v1",
  "  prompthub doctor database-lock --recover",
  "",
  "更多帮助:",
  "  prompthub prompt --help",
  "  prompthub agent --help",
  "  prompthub rules --help",
  "  prompthub skill --help",
  "  prompthub mcp --help",
  "  prompthub plugin --help",
  "  prompthub sync --help",
  "  prompthub ai --help",
].join("\n");

export const AGENT_HELP = [
  "Agent 命令",
  "",
  "用法:",
  "  prompthub agent list [--filter <filter>] [--search <query>] [--include-disabled]",
  "  prompthub agent get <id|name|query> [--include-disabled]",
  "  prompthub agent enable <id|name|query>",
  "  prompthub agent disable <id|name|query>",
  "  prompthub agent add --name <name> --root <path> [--id <id>] [path options]",
  "  prompthub agent update <custom-agent> [--name <name>] [--root <path>] [--enabled|--disabled] [path options]",
  "  prompthub agent configure <agent> [--root <path>] [path options]",
  "  prompthub agent reset <built-in-agent>",
  "  prompthub agent delete <custom-agent>",
  "  prompthub agent identity get",
  "  prompthub agent identity set --name codex|chatgpt [--icon codex|chatgpt]",
  "  prompthub agent config list <agent> [--include-disabled]",
  "  prompthub agent config read <agent> <relative-path> [--include-disabled]",
  "",
  "filter:",
  "  all | installed | configured | custom | not-detected | needs-attention",
  "",
  "path options:",
  "  --root <path>",
  "  --skills-path <relative-path>",
  "  --mcp-path <relative-path>",
  "  --plugins-path <relative-path>",
  "  --rules-path <relative-path>",
  "  --agents-path <relative-path>",
  "  --commands-path <relative-path>",
  "  --config-paths <relative-path,...>",
  "",
  "说明:",
  "  Agent identity、custom Agent、禁用状态和 built-in override 与桌面端共享 SQLite settings。",
  "  delete 只删除 custom Agent 记录，不删除 Agent 根目录或平台运行时数据。",
  "  config list/read 安全检查 Agent 原生配置；读取结果会脱敏，且不会修改源文件。",
  "  capability 状态来自共享 Agent inventory；planned/partial 不会被伪装成 supported。",
].join("\n");

export const SYNC_HELP = [
  "Sync 命令",
  "",
  "用法:",
  "  prompthub sync status --endpoint <url> --token <token>",
  "  prompthub sync push --endpoint <url> --token <token>",
  "  prompthub sync pull --endpoint <url> --token <token> [--force-clear]",
  "",
  "说明:",
  "  endpoint 指向自部署 Web 或 Cloudflare Worker 根地址，例如 https://prompthub.example.com。",
  "  token 可通过 --token、PROMPTHUB_SYNC_TOKEN 或 PROMPTHUB_TOKEN 提供。",
  "  endpoint 可通过 --endpoint 或 PROMPTHUB_SYNC_ENDPOINT 提供。",
  "  push/pull 使用与 workspace export/import 相同的 SyncSnapshot 兼容快照。",
].join("\n");

export const PROMPT_HELP = [
  "Prompt 命令",
  "",
  "用法:",
  "  prompthub prompt list",
  "  prompthub prompt get <id|title|query>",
  "  prompthub prompt duplicate <id|title|query>",
  "  prompthub prompt versions <id|title|query>",
  "  prompthub prompt create-version <id|title|query> [--note <text>]",
  "  prompthub prompt delete-version <id|title|query> <version-id>",
  "  prompthub prompt diff <id|title|query> --from <n> --to <n>",
  "  prompthub prompt rollback <id|title|query> --version <n>",
  "  prompthub prompt use [id|title|query]",
  "  prompthub prompt copy [id|title|query] [--var name=value]...",
  "  prompthub prompt list-tags",
  "  prompthub prompt rename-tag <old> <new>",
  "  prompthub prompt delete-tag <tag>",
  "  prompthub prompt create --title <title> --user-prompt <text> [--parent-id <id>]",
  "  prompthub prompt update <id> [fields...] [--parent-id <id>]",
  "  prompthub prompt delete <id>",
  "  prompthub prompt search [keyword] [filters...]",
  "  prompthub prompt relation list [--prompt-id <id>] [--kind related_to|variant_of|depends_on|next_step]",
  "  prompthub prompt relation create --source <id> --target <id> --kind related_to|variant_of|depends_on|next_step [--note <text>]",
  "  prompthub prompt relation update <relation-id> [--kind related_to|variant_of|depends_on|next_step] [--note <text>]",
  "  prompthub prompt relation delete <relation-id>",
  "  prompthub prompt output-format list [--source <prompt-id>]",
  "  prompthub prompt output-format create --source <prompt-id> [--target <prompt-id>] [--sort-order <n>]",
  "  prompthub prompt output-format delete <item-id>",
  "  prompthub prompt output-format reorder --source <prompt-id> --id <item-id> --sort-order <n>",
  "",
  "常用参数:",
  "  --title <text>",
  "  --visibility private|shared",
  "  --description <text>",
  "  --user-prompt <text> | --user-prompt-file <file>",
  "  --user-prompt-en <text> | --user-prompt-en-file <file>",
  "  --system-prompt <text> | --system-prompt-file <file>",
  "  --system-prompt-en <text> | --system-prompt-en-file <file>",
  "  --variables <json> | --variables-file <file>",
  "  --tags a,b",
  "  --images a,b",
  "  --videos a,b",
  "  --folder-id <id>",
  "  --parent-id <id>        Prompt 树父节点",
  "  --prompt-type text|image|video",
  "  --favorite / --unfavorite",
  "  --pinned / --unpinned",
  "  --scope private|shared|all",
  "  --usage-count <n>",
  "  --last-ai-response <text> | --last-ai-response-file <file>",
  "  --sort-by title|createdAt|updatedAt|usageCount",
  "  --sort-order asc|desc",
  "  --limit <n> --offset <n>",
  "  --version <n>           用于 rollback 指定目标版本",
  "  --from <n> / --to <n>   用于 diff 指定版本区间",
  "  --note <text>           用于 create-version 添加版本备注",
  "",
  "示例:",
  "  prompthub prompt list",
  "  prompthub prompt get 2b8d...",
  "  prompthub prompt duplicate 2b8d...",
  "  prompthub prompt versions 2b8d...",
  '  prompthub prompt create-version 2b8d... --note "Before refactor"',
  "  prompthub prompt delete-version 2b8d... 91f1...",
  "  prompthub prompt diff 2b8d... --from 1 --to 3",
  "  prompthub prompt rollback 2b8d... --version 3",
  "  prompthub prompt use 2b8d...",
  "  prompthub prompt copy 2b8d... --var tone=direct --var audience=devs",
  "  prompthub prompt list-tags",
  "  prompthub prompt rename-tag seo marketing",
  '  prompthub prompt create --title "SEO Blog" --user-prompt-file ./seo.md --tags writing,seo',
  '  prompthub prompt update 2b8d... --favorite --title "SEO Blog v2"',
  "  prompthub --output table prompt search SEO --favorite",
].join("\n");

export const SKILL_HELP = [
  "Skill 命令",
  "",
  "用法:",
  "  prompthub skill list",
  "  prompthub skill get <id|name>",
  "  prompthub skill import <github-url|local-dir|SKILL.md|json>",
  "  prompthub skill project-install [id|name|query] [--project <path>] [--target <skills-dir>] [--force]",
  "  prompthub skill install-project [id|name|query] [--project <path>] [--target <skills-dir>] [--force]",
  "  prompthub skill scan [custom-path...]",
  "  prompthub skill versions <id|name>",
  "  prompthub skill create-version <id|name> [--note <text>]",
  "  prompthub skill rollback <id|name> --version <n>",
  "  prompthub skill delete-version <id|name> <version-id>",
  "  prompthub skill export <id|name> --format skillmd|json",
  "  prompthub skill platforms",
  "  prompthub skill platform-status <id|name>",
  "  prompthub skill distribute <id|name> --platform <platform-id>",
  "  prompthub skill undistribute <id|name> --platform <platform-id>",
  "  prompthub skill repo-files <id|name>",
  "  prompthub skill repo-read <id|name> --path <relative-path>",
  "  prompthub skill repo-write <id|name> --path <relative-path> --content <text>",
  "  prompthub skill repo-delete <id|name> --path <relative-path>",
  "  prompthub skill repo-mkdir <id|name> --path <relative-path>",
  "  prompthub skill repo-rename <id|name> --from <old> --to <new>",
  "  prompthub skill sync-from-repo <id|name>",
  "  prompthub skill scan-safety <id|name>",
  "  prompthub skill update <id|name> [--description <text>] [--version <text>] [--author <text>] [--tags a,b]",
  "  prompthub skill check-update <id|name> [--fetch-remote]",
  "  prompthub skill delete <id|name> [options]",
  "  prompthub skill remove <id|name> [options]",
  "",
  "delete/remove 语义:",
  "  默认会删除 PromptHub 中的 skill 记录，并尝试从已支持平台卸载 SKILL.md。",
  "  不会默认删除本地源码目录；若目标 repo 位于 PromptHub 管理目录内，可额外加 --purge-managed-repo。",
  "",
  "删除参数:",
  "  --keep-platform-installs  不从 Claude/Cursor 等平台卸载",
  "  --purge-managed-repo      同时删除 PromptHub 管理目录中的本地 repo",
  "",
  "安装参数:",
  "  --name <text>             本地 SKILL.md/目录缺少 frontmatter name 时手动指定",
  "  --format skillmd|json     用于 export 指定导出格式",
  "  --platform <platform-id>  指定目标平台",
  "  --project <path>          项目根目录；默认当前工作目录",
  "  --target <path>           直接指定项目 skills 目标目录；默认 <project>/.agents/skills",
  "  --mode copy|symlink       项目安装模式；默认 copy",
  "  --force                   项目中已存在同名 Skill 时覆盖刷新",
  "  --path <relative-path>    指定 repo 内相对路径",
  "  --from <old> --to <new>   用于 repo-rename",
  "  --content <text> | --content-file <file>",
  "  --note <text>             用于 create-version 添加版本备注",
  "  --version <n>             用于 rollback 指定目标版本",
  "  --fetch-remote            check-update 时拉取 content_url 比对远端",
  "",
  "兼容别名:",
  "  install = import，install-md = distribute，uninstall-md = undistribute",
  "",
  "示例:",
  "  prompthub skill list",
  "  prompthub skill import https://github.com/foo/bar",
  "  prompthub skill import ~/.claude/skills/writer --name writer",
  "  prompthub skill project-install",
  "  prompthub skill project-install writer --force",
  "  prompthub skill versions writer",
  "  prompthub skill export writer --format skillmd",
  '  prompthub skill update writer --description "Improved writer"',
  "  prompthub skill check-update writer",
  "  prompthub skill platform-status writer",
  "  prompthub skill delete writer --purge-managed-repo",
  "  prompthub skill remove writer --keep-platform-installs",
  "  prompthub --output table skill scan ~/.claude/skills",
].join("\n");

export const MCP_HELP = [
  "MCP 命令",
  "",
  "用法:",
  "  prompthub mcp list",
  "  prompthub mcp get <id|name>",
  "  prompthub mcp create --name <name> [--transport stdio|sse|streamable-http] [--command <cmd>] [--args a,b] [--url <url>]",
  "  prompthub mcp update <id|name> [fields...]",
  "  prompthub mcp delete <id|name>",
  "  prompthub mcp market",
  "  prompthub mcp sources",
  "  prompthub mcp install [template-id|name|query]",
  "  prompthub mcp import <file>",
  "  prompthub mcp check [id|name]",
  "  prompthub mcp env-import <id|name> --file <.env> [--keys A,B]",
  "  prompthub mcp enable <id|name>",
  "  prompthub mcp disable <id|name>",
  "  prompthub mcp export --target <target> [--servers a,b]",
  "  prompthub mcp apply --preset <preset-id> [--servers id,name,query] [--force]",
  "  prompthub mcp apply --target <target> --path <file> [--servers id,name,query] [--force]",
  "  prompthub mcp remove --preset <preset-id> --servers id,name,query",
  "",
  "说明:",
  "  MCP CLI 读写与桌面端相同的 PromptHub MCP library。",
  "  env-import 只导入当前 MCP 需要的 key，或 --keys 明确指定的 key。",
  "  apply 默认拒绝覆盖目标配置中的外部同名 MCP；确认覆盖时使用 --force。",
].join("\n");

export const FOLDER_HELP = [
  "Folder 命令",
  "",
  "用法:",
  "  prompthub folder list",
  "  prompthub folder get <id>",
  "  prompthub folder create --name <name>",
  "  prompthub folder update <id> [fields...]",
  "  prompthub folder delete <id>",
  "  prompthub folder reorder --ids <id1,id2,...>",
  "",
  "常用参数:",
  "  --name <text>",
  "  --icon <emoji>",
  "  --parent-id <id>",
  "  --order <n>",
  "  --private / --public",
  "  --ids a,b,c",
  "",
  "示例:",
  "  prompthub folder list",
  "  prompthub folder create --name Writing --icon ✍️",
  "  prompthub folder update 2b8d... --name Research --parent-id root-folder",
  "  prompthub folder reorder --ids folder-a,folder-b,folder-c",
].join("\n");

export const WORKSPACE_HELP = [
  "Workspace 命令",
  "",
  "用法:",
  "  prompthub workspace export --file <path>",
  "  prompthub workspace import --file <path> [--force-clear]",
  "",
  "说明:",
  "  导出 SyncSnapshot 兼容快照，覆盖 prompts、folders、versions、relations、output-formats、",
  "  rules、skills（含 skillFiles 包内容）、My MCP、My Plugin 和可用媒体文件。",
  "  import 默认要求目标数据库为空；使用 --force-clear 才会先清空现有本地数据。",
  "",
  "参数:",
  "  --file <path>",
  "  --force-clear",
  "",
  "示例:",
  "  prompthub workspace export --file ./prompthub-workspace.json",
  "  prompthub workspace import --file ./prompthub-workspace.json --force-clear",
].join("\n");

export const RULES_HELP = [
  "Rules 命令",
  "",
  "用法:",
  "  prompthub rules list",
  "  prompthub rules scan",
  "  prompthub rules read [rule-id|name|query]",
  "  prompthub rules versions <rule-id|name|query>",
  "  prompthub rules version-read <rule-id|name|query> <version-id>",
  "  prompthub rules version-restore <rule-id|name|query> <version-id>",
  "  prompthub rules save <rule-id|name|query> --content <text>",
  "  prompthub rules rewrite <rule-id|name|query> --instruction <text> --api-key <key> --api-url <url> --model <model>",
  "  prompthub rules project-init [--name <name>] [--root-path <path>] [--id <id>]",
  "  prompthub rules add-project [--name <name>] [--root-path <path>] [--id <id>]",
  "  prompthub rules remove-project <project-id>",
  "  prompthub rules version-delete <rule-id> <version-id>",
  "  prompthub rules export --file <path>",
  "  prompthub rules import --file <path> [--replace]",
  "",
  "常用参数:",
  "  --content <text> | --content-file <file>",
  "  --instruction <text> | --instruction-file <file>",
  "  --api-key <text>",
  "  --api-url <url>",
  "  --model <text>",
  "  --provider <text>",
  "  --api-protocol openai|gemini|anthropic",
  "  --name <text>",
  "  --root-path <path>",
  "  --id <text>",
  "  --file <path>",
  "  --replace",
  "",
  "示例:",
  "  prompthub rules list",
  "  prompthub rules scan",
  "  prompthub rules versions claude-global",
  "  prompthub rules version-read claude-global abc123",
  "  prompthub rules version-restore claude-global abc123",
  '  prompthub rules save claude-global --content "# Team Claude rules"',
  '  prompthub rules rewrite claude-global --instruction "Tighten the tone" --api-key "$OPENAI_API_KEY" --api-url https://api.openai.com/v1 --model gpt-4o-mini',
  '  prompthub rules add-project --name "Docs Site" --root-path ./docs-site',
  "  prompthub rules remove-project docs-site",
  "  prompthub rules export --file ./prompthub-rules.json",
].join("\n");
