/**
 * IPC channel definitions
 */

export const IPC_CHANNELS = {
  // Prompt
  PROMPT_CREATE: "prompt:create",
  PROMPT_GET: "prompt:get",
  PROMPT_GET_ALL: "prompt:getAll",
  PROMPT_GET_ALL_META: "prompt:getAllMeta",
  PROMPT_GET_ALL_TAGS: "prompt:getAllTags",
  PROMPT_RENAME_TAG: "prompt:renameTag",
  PROMPT_DELETE_TAG: "prompt:deleteTag",
  PROMPT_UPDATE: "prompt:update",
  PROMPT_DELETE: "prompt:delete",
  PROMPT_SEARCH: "prompt:search",
  PROMPT_COPY: "prompt:copy",
  PROMPT_INSERT_DIRECT: "prompt:insertDirect",
  PROMPT_RESTORE_GRAPH: "prompt:restoreGraph",
  PROMPT_SYNC_WORKSPACE: "prompt:syncWorkspace",
  /**
   * Atomic batch migration from legacy IndexedDB data.
   * All inserts are wrapped in a single SQLite transaction.
   * Returns { imported: true } when data was actually written, or { imported: false } if
   * the target already had prompts (no-op guard).
   *
   * 原子批量迁移：将旧版 IndexedDB 数据一次性写入 SQLite（单事务）。
   * 若 SQLite 已有数据则直接返回 { imported: false }（防止覆盖）。
   */
  PROMPT_MIGRATE_IDB_BATCH: "prompt:migrateIdbBatch",
  PROMPT_MOVE: "prompt:move",
  PROMPT_RELATION_CREATE: "promptRelation:create",
  PROMPT_RELATION_INSERT_DIRECT: "promptRelation:insertDirect",
  PROMPT_RELATION_LIST: "promptRelation:list",
  PROMPT_RELATION_UPDATE: "promptRelation:update",
  PROMPT_RELATION_DELETE: "promptRelation:delete",
  PROMPT_OUTPUT_FORMAT_CREATE: "promptOutputFormat:create",
  PROMPT_OUTPUT_FORMAT_INSERT_DIRECT: "promptOutputFormat:insertDirect",
  PROMPT_OUTPUT_FORMAT_LIST: "promptOutputFormat:list",
  PROMPT_OUTPUT_FORMAT_UPDATE: "promptOutputFormat:update",
  PROMPT_OUTPUT_FORMAT_DELETE: "promptOutputFormat:delete",
  PROMPT_OUTPUT_FORMAT_REORDER: "promptOutputFormat:reorder",

  // Version
  VERSION_GET_ALL: "version:getAll",
  VERSION_CREATE: "version:create",
  VERSION_ROLLBACK: "version:rollback",
  VERSION_DIFF: "version:diff",
  VERSION_DELETE: "version:delete",
  VERSION_INSERT_DIRECT: "version:insertDirect",

  // Folder
  FOLDER_CREATE: "folder:create",
  FOLDER_GET_ALL: "folder:getAll",
  FOLDER_UPDATE: "folder:update",
  FOLDER_DELETE: "folder:delete",
  FOLDER_REORDER: "folder:reorder",
  FOLDER_INSERT_DIRECT: "folder:insertDirect",

  // Settings
  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SETTINGS_RENDERER_PERSISTENCE_MIGRATE: "settings:rendererPersistence:migrate",
  SETTINGS_RENDERER_PERSISTENCE_GET: "settings:rendererPersistence:get",
  SETTINGS_RENDERER_PERSISTENCE_REPLACE_SETTINGS:
    "settings:rendererPersistence:replaceSettings",
  SETTINGS_RENDERER_PERSISTENCE_REPLACE_SOURCES:
    "settings:rendererPersistence:replaceSources",
  SETTINGS_RENDERER_PERSISTENCE_REPLACE_RECOVERY_PATHS:
    "settings:rendererPersistence:replaceRecoveryPaths",
  SETTINGS_RENDERER_PERSISTENCE_DEVICE_ID:
    "settings:rendererPersistence:deviceId",
  SETTINGS_RENDERER_PERSISTENCE_IDB_STATUS:
    "settings:rendererPersistence:idbStatus",
  SETTINGS_RENDERER_PERSISTENCE_IDB_DONE:
    "settings:rendererPersistence:idbDone",

  // PromptHub Cloud account and Store
  CLOUD_AUTH_GET_STATE: "cloud:auth:getState",
  CLOUD_AUTH_LOGIN: "cloud:auth:login",
  CLOUD_AUTH_LOGOUT: "cloud:auth:logout",
  CLOUD_ACCOUNT_OVERVIEW: "cloud:account:overview",
  CLOUD_ACCOUNT_PROFILE: "cloud:account:profile",
  CLOUD_ACCOUNT_PASSWORD: "cloud:account:password",
  CLOUD_ACCOUNT_VERIFY_EMAIL: "cloud:account:verifyEmail",
  CLOUD_ACCOUNT_SESSIONS: "cloud:account:sessions",
  CLOUD_ACCOUNT_REVOKE_SESSION: "cloud:account:revokeSession",
  CLOUD_ACCOUNT_REVOKE_OTHERS: "cloud:account:revokeOthers",
  CLOUD_ACCOUNT_EXPORT: "cloud:account:export",
  CLOUD_ACCOUNT_EXPORT_DOWNLOAD: "cloud:account:exportDownload",
  CLOUD_ACCOUNT_DELETE: "cloud:account:delete",
  CLOUD_ACCOUNT_CANCEL_DELETE: "cloud:account:cancelDelete",
  CLOUD_ACCOUNT_ENTITLEMENTS: "cloud:account:entitlements",
  CLOUD_STORE_FEED: "cloud:store:feed",
  CLOUD_STORE_LISTING: "cloud:store:listing",
  CLOUD_STORE_PACKAGE: "cloud:store:package",
  CLOUD_STORE_INSTALL_INTENT: "cloud:store:installIntent",
  CLOUD_STORE_INSTALL_STATUS: "cloud:store:installStatus",
  CLOUD_STORE_INSTALLATIONS: "cloud:store:installations",
  CLOUD_STORE_LIKE: "cloud:store:like",
  CLOUD_STORE_UNLIKE: "cloud:store:unlike",
  CLOUD_STORE_FAVORITE: "cloud:store:favorite",
  CLOUD_STORE_UNFAVORITE: "cloud:store:unfavorite",
  CLOUD_STORE_REPORT: "cloud:store:report",

  // CLI
  CLI_STATUS: "cli:status",
  CLI_INSTALL: "cli:install",

  // Rules
  RULES_LIST: "rules:list",
  RULES_SCAN: "rules:scan",
  RULES_READ: "rules:read",
  RULES_SAVE: "rules:save",
  RULES_RESOLVE_CONFLICT: "rules:resolveConflict",
  RULES_REWRITE: "rules:rewrite",
  RULES_ADD_PROJECT: "rules:addProject",
  RULES_REMOVE_PROJECT: "rules:removeProject",
  RULES_REMOVE_MISSING_PROJECTS: "rules:removeMissingProjects",
  RULES_IMPORT_RECORDS: "rules:importRecords",
  RULES_VERSION_DELETE: "rules:version:delete",

  // App lifecycle
  APP_RELAUNCH: "app:relaunch",
  APP_GET_CACHE_SIZE: "app:getCacheSize",
  APP_CLEAR_CACHE: "app:clearCache",
  APP_GET_RUNTIME_PATHS: "app:getRuntimePaths",
  APP_APPEND_AUTO_SYNC_LOG: "app:appendAutoSyncLog",
  APP_COMMAND: "app:command",

  // AI transport
  AI_HTTP_REQUEST: "ai:httpRequest",
  AI_HTTP_STREAM: "ai:httpStream",
  AI_HTTP_STREAM_CHUNK: "ai:httpStreamChunk",
  AI_HTTP_STREAM_ERROR: "ai:httpStreamError",

  // Local image generation workbench
  GENERATION_LIST: "generation:list",
  GENERATION_GET: "generation:get",
  GENERATION_CREATE: "generation:create",
  GENERATION_SLOT_RUNNING: "generation:slotRunning",
  GENERATION_COMMIT_OUTPUT: "generation:commitOutput",
  GENERATION_COMMIT_REMOTE_OUTPUT: "generation:commitRemoteOutput",
  GENERATION_FAIL_SLOT: "generation:failSlot",
  GENERATION_CANCEL: "generation:cancel",
  GENERATION_SET_FAVORITE: "generation:setFavorite",
  GENERATION_RETRY_FAILED: "generation:retryFailed",
  GENERATION_COPY_TO_PROMPT_MEDIA: "generation:copyToPromptMedia",
  GENERATION_READ_OUTPUT_REFERENCE: "generation:readOutputReference",

  // Import/Export
  EXPORT_PROMPTS: "export:prompts",
  IMPORT_PROMPTS: "import:prompts",

  // Security / Encryption
  SECURITY_SET_MASTER_PASSWORD: "security:setMasterPassword",
  SECURITY_CHANGE_MASTER_PASSWORD: "security:changeMasterPassword",
  SECURITY_UNLOCK: "security:unlock",
  SECURITY_STATUS: "security:status",
  SECURITY_LOCK: "security:lock",

  // Skills
  SKILL_CREATE: "skill:create",
  SKILL_GET: "skill:get",
  SKILL_GET_ALL: "skill:getAll",
  SKILL_UPDATE: "skill:update",
  SKILL_DELETE: "skill:delete",
  SKILL_SEARCH: "skill:search",
  SKILL_EXPORT: "skill:export",
  SKILL_EXPORT_ZIP: "skill:exportZip",
  SKILL_IMPORT: "skill:import",
  SKILL_SCAN_LOCAL: "skill:scanLocal",
  SKILL_SCAN_LOCAL_PREVIEW: "skill:scanLocalPreview",
  SKILL_SCAN_SAFETY: "skill:scanSafety",
  SKILL_SAVE_SAFETY_REPORT: "skill:saveSafetyReport",
  SKILL_INSTALL_TO_PLATFORM: "skill:installToPlatform",
  SKILL_UNINSTALL_FROM_PLATFORM: "skill:uninstallFromPlatform",
  SKILL_GET_PLATFORM_STATUS: "skill:getPlatformStatus",

  // SKILL.md Multi-Platform Installation
  SKILL_GET_SUPPORTED_PLATFORMS: "skill:getSupportedPlatforms",
  SKILL_DETECT_PLATFORMS: "skill:detectPlatforms",
  SKILL_SCAN_PLATFORM_SKILLS: "skill:scanPlatformSkills",
  SKILL_UNINSTALL_PLATFORM_SKILL: "skill:uninstallPlatformSkill",
  SKILL_INSTALL_MD: "skill:installMd",
  SKILL_UNINSTALL_MD: "skill:uninstallMd",
  SKILL_GET_MD_INSTALL_STATUS: "skill:getMdInstallStatus",
  SKILL_GET_MD_INSTALL_STATUS_BATCH: "skill:getMdInstallStatusBatch",
  SKILL_GET_MD_INSTALL_STATUS_DETAILS: "skill:getMdInstallStatusDetails",
  SKILL_INSTALL_MD_SYMLINK: "skill:installMdSymlink",
  SKILL_FETCH_REMOTE_CONTENT: "skill:fetchRemoteContent",
  SKILL_FETCH_REMOTE_CONTENT_BYTES: "skill:fetchRemoteContentBytes",
  SKILL_SCAN_REMOTE_GITHUB: "skill:scanRemoteGithub",
  SKILL_LIST_REMOTE_BRANCHES: "skill:listRemoteBranches",

  // Agent native configuration files
  AGENT_CONFIG_FILES_LIST: "agent:configFiles:list",
  AGENT_LAUNCH: "agent:launch",
  AGENT_CONFIG_FILE_READ: "agent:configFile:read",
  AGENT_CONFIG_FILE_WRITE: "agent:configFile:write",
  AGENT_DEFINITIONS_LIST: "agent:definitions:list",
  AGENT_DEFINITION_OPEN: "agent:definition:open",
  AGENT_HARNESS_PROFILES_LIST: "agent:harnessProfiles:list",
  AGENT_HARNESS_PROFILE_READ: "agent:harnessProfile:read",
  AGENT_HARNESS_PLUGIN_MUTATE: "agent:harnessPlugin:mutate",
  AGENT_MODEL_CONFIG_GET: "agent:modelConfig:get",
  AGENT_MODEL_CONFIG_SET: "agent:modelConfig:set",
  AGENT_PI_PROVIDER_ADD: "agent:pi:provider:add",
  AGENT_PI_PROVIDER_IMPORT_CURRENT: "agent:pi:provider:importCurrent",
  AGENT_PI_PROVIDER_SOURCE_IMPORT: "agent:pi:providerSource:import",
  AGENT_PI_PROVIDER_UPDATE: "agent:pi:provider:update",
  AGENT_PI_PROVIDER_REMOVE: "agent:pi:provider:remove",
  AGENT_PI_MODEL_ADD: "agent:pi:model:add",
  AGENT_PI_MODEL_UPDATE: "agent:pi:model:update",
  AGENT_PI_MODEL_REMOVE: "agent:pi:model:remove",
  AGENT_PI_MODEL_TEST: "agent:pi:model:test",
  AGENT_PI_CREDENTIAL_SET: "agent:pi:credential:set",
  AGENT_SESSIONS_LIST: "agent:sessions:list",
  AGENT_SESSION_READ: "agent:session:read",
  AGENT_SESSION_INDEX_GET_STATE: "agent:sessionIndex:getState",
  AGENT_SESSION_INDEX_SET_ENABLED: "agent:sessionIndex:setEnabled",
  AGENT_SESSION_INDEX_REFRESH: "agent:sessionIndex:refresh",
  AGENT_SESSION_INDEX_CANCEL: "agent:sessionIndex:cancel",
  AGENT_SESSION_INDEX_PROGRESS: "agent:sessionIndex:progress",
  AGENT_CONVERSATION_METADATA_LIST: "agent:conversationMetadata:list",
  AGENT_CONVERSATION_METADATA_UPDATE: "agent:conversationMetadata:update",
  AGENT_CONVERSATION_DELETE: "agent:conversation:delete",
  AGENT_CONVERSATION_RESUME: "agent:conversation:resume",
  AGENT_CONVERSATION_HANDOFF_PREVIEW: "agent:conversation:handoffPreview",
  AGENT_CONVERSATION_HANDOFF_CONTINUE: "agent:conversation:handoffContinue",
  AGENT_CONVERSATION_EXPORT: "agent:conversation:export",
  AGENT_USAGE_GET: "agent:usage:get",
  AGENT_PROVIDER_PROFILES_LIST: "agent:providerProfiles:list",
  AGENT_PROVIDER_PROFILES_CREATE: "agent:providerProfiles:create",
  AGENT_PROVIDER_PROFILES_UPDATE: "agent:providerProfiles:update",
  AGENT_PROVIDER_PROFILES_ARCHIVE: "agent:providerProfiles:archive",
  AGENT_PROVIDER_PROFILES_DUPLICATE: "agent:providerProfiles:duplicate",
  AGENT_PROVIDER_PROFILES_EXPORT: "agent:providerProfiles:export",
  AGENT_PROVIDER_PROFILES_DELETE: "agent:providerProfiles:delete",
  AGENT_PROVIDER_SOURCES_LIST: "agent:providerSources:list",
  AGENT_PROVIDER_SOURCE_IMPORT: "agent:providerSources:import",
  AGENT_PROVIDER_OFFICIAL_ENSURE: "agent:providerSources:ensureOfficial",
  AGENT_MANAGEMENT_BACKUP_EXPORT: "agent:managementBackup:export",
  AGENT_MANAGEMENT_BACKUP_RESTORE: "agent:managementBackup:restore",
  AGENT_PROVIDER_CURRENT_STATE: "agent:provider:currentState",
  AGENT_CODEX_ACCOUNTS_LIST: "agent:codexAccounts:list",
  AGENT_CODEX_ACCOUNT_SAVE_CURRENT: "agent:codexAccounts:saveCurrent",
  AGENT_CODEX_ACCOUNT_IMPORT: "agent:codexAccounts:import",
  AGENT_CODEX_ACCOUNT_ACTIVATE: "agent:codexAccounts:activate",
  AGENT_CODEX_ACCOUNT_DELETE: "agent:codexAccounts:delete",
  AGENT_PROVIDER_MIGRATION_PREVIEW: "agent:providerMigration:preview",
  AGENT_PROVIDER_MIGRATION_APPLY: "agent:providerMigration:apply",
  AGENT_PROVIDER_IMPORT_CURRENT: "agent:provider:importCurrent",
  AGENT_PROVIDER_TEST_CURRENT_CONNECTION:
    "agent:provider:testCurrentConnection",
  AGENT_PROVIDER_TEST_CURRENT_MODEL: "agent:provider:testCurrentModel",
  AGENT_PROVIDER_TEST_CONNECTION: "agent:provider:testConnection",
  AGENT_PROVIDER_TEST_MODEL: "agent:provider:testModel",
  AGENT_PROVIDER_CANCEL_MODEL_TEST: "agent:provider:cancelModelTest",
  AGENT_PROVIDER_PREVIEW: "agent:provider:preview",
  AGENT_PROVIDER_ACTIVATE: "agent:provider:activate",
  AGENT_APPEARANCE_GET: "agent:appearance:get",
  AGENT_APPEARANCE_IMPORT_THEME: "agent:appearance:theme:import",
  AGENT_APPEARANCE_APPLY_THEME: "agent:appearance:theme:apply",
  AGENT_APPEARANCE_RESTORE_THEME: "agent:appearance:theme:restore",
  AGENT_APPEARANCE_DELETE_THEME: "agent:appearance:theme:delete",
  AGENT_APPEARANCE_EXPORT_THEME: "agent:appearance:theme:export",
  AGENT_APPEARANCE_THEME_PREVIEW: "agent:appearance:theme:preview",
  AGENT_APPEARANCE_IMPORT_PET: "agent:appearance:pet:import",
  AGENT_APPEARANCE_EXPORT_PET: "agent:appearance:pet:export",
  AGENT_APPEARANCE_DELETE_PET: "agent:appearance:pet:delete",
  AGENT_APPEARANCE_PET_PREVIEW: "agent:appearance:pet:preview",
  AGENT_APPEARANCE_UPDATE_PET: "agent:appearance:pet:update",
  AGENT_APPEARANCE_PET_STORE_LIST: "agent:appearance:pet-store:list",
  AGENT_APPEARANCE_PET_STORE_INSTALL: "agent:appearance:pet-store:install",
  AGENT_APPEARANCE_PET_STORE_PREVIEW: "agent:appearance:pet-store:preview",

  // Skill Local Repo Storage
  SKILL_LIST_LOCAL_FILES: "skill:listLocalFiles",
  SKILL_READ_LOCAL_FILE: "skill:readLocalFile",
  SKILL_READ_LOCAL_FILES: "skill:readLocalFiles",
  SKILL_RENAME_LOCAL_PATH: "skill:renameLocalPath",
  SKILL_WRITE_LOCAL_FILE: "skill:writeLocalFile",
  SKILL_DELETE_LOCAL_FILE: "skill:deleteLocalFile",
  SKILL_CREATE_LOCAL_DIR: "skill:createLocalDir",
  SKILL_LIST_LOCAL_FILES_BY_PATH: "skill:listLocalFilesByPath",
  SKILL_READ_LOCAL_FILE_BY_PATH: "skill:readLocalFileByPath",
  SKILL_RENAME_LOCAL_PATH_BY_PATH: "skill:renameLocalPathByPath",
  SKILL_WRITE_LOCAL_FILE_BY_PATH: "skill:writeLocalFileByPath",
  SKILL_WRITE_LOCAL_FILE_BUFFER_BY_PATH: "skill:writeLocalFileBufferByPath",
  SKILL_DELETE_LOCAL_FILE_BY_PATH: "skill:deleteLocalFileByPath",
  SKILL_GET_LOCAL_PATH_STATUS: "skill:getLocalPathStatus",
  SKILL_CREATE_LOCAL_DIR_BY_PATH: "skill:createLocalDirByPath",
  SKILL_COPY_REPO_BY_PATH_TO_DIRECTORY: "skill:copyRepoByPathToDirectory",
  SKILL_SAVE_TO_REPO: "skill:saveToRepo",
  SKILL_SAVE_REMOTE_GIT_TO_REPO: "skill:saveRemoteGitToRepo",
  SKILL_SAVE_REMOTE_ZIP_TO_REPO: "skill:saveRemoteZipToRepo",
  SKILL_RUN_PACKAGE_OPERATION: "skill:runPackageOperation",
  SKILL_GET_REMOTE_GIT_PACKAGE_FINGERPRINT:
    "skill:getRemoteGitPackageFingerprint",
  SKILL_GET_REMOTE_GIT_PACKAGE_SNAPSHOT: "skill:getRemoteGitPackageSnapshot",
  SKILL_GET_REMOTE_ZIP_PACKAGE_SNAPSHOT: "skill:getRemoteZipPackageSnapshot",
  SKILL_GET_LOCAL_PACKAGE_FINGERPRINT: "skill:getLocalPackageFingerprint",
  SKILL_GET_LOCAL_PACKAGE_SNAPSHOT: "skill:getLocalPackageSnapshot",
  SKILL_GET_REPO_PATH: "skill:getRepoPath",
  SKILL_SYNC_FROM_REPO: "skill:syncFromRepo",

  // Skill Version
  SKILL_VERSION_GET_ALL: "skill:version:getAll",
  SKILL_VERSION_CREATE: "skill:version:create",
  SKILL_VERSION_ROLLBACK: "skill:version:rollback",
  SKILL_VERSION_DELETE: "skill:version:delete",
  // Skill Backup Restore
  SKILL_DELETE_ALL: "skill:deleteAll",
  SKILL_INSERT_VERSION_DIRECT: "skill:version:insertDirect",

  // MCP
  MCP_LIBRARY_GET: "mcp:library:get",
  MCP_LIBRARY_REPLACE: "mcp:library:replace",
  MCP_LIBRARY_EXPORT_FILES: "mcp:library:exportFiles",
  MCP_LIBRARY_RESTORE_FILES: "mcp:library:restoreFiles",
  MCP_MARKET_LIST: "mcp:market:list",
  MCP_MARKET_SOURCES: "mcp:market:sources",
  MCP_MARKET_SOURCES_REPLACE: "mcp:market:sources:replace",
  MCP_MARKET_INSTALL_TEMPLATE: "mcp:market:installTemplate",
  MCP_MARKET_CHECK_UPDATE: "mcp:market:checkUpdate",
  MCP_MARKET_APPLY_UPDATE: "mcp:market:applyUpdate",
  MCP_FETCH_REMOTE_CONTENT: "mcp:fetchRemoteContent",
  MCP_TARGET_PRESETS: "mcp:target:presets",
  MCP_SERVER_CREATE: "mcp:server:create",
  MCP_SERVER_CREATE_FROM_SOURCE: "mcp:server:createFromSource",
  MCP_SERVER_UPDATE: "mcp:server:update",
  MCP_SERVER_DELETE: "mcp:server:delete",
  MCP_TEMPLATE_INSTALL: "mcp:template:install",
  MCP_PREVIEW: "mcp:preview",
  MCP_APPLY: "mcp:apply",
  MCP_REMOVE: "mcp:remove",
  MCP_REMOVE_NAMES: "mcp:remove:names",
  MCP_TARGET_STATUS: "mcp:target:status",
  MCP_IMPORT_FILE: "mcp:importFile",
  MCP_HEALTH_CHECK: "mcp:health:check",
  MCP_HEALTH_CHECK_ALL: "mcp:health:checkAll",
  MCP_ENV_IMPORT: "mcp:env:import",
  MCP_TARGET_SYNC_CHECK: "mcp:targetSync:check",
  MCP_TARGET_SYNC_APPLY: "mcp:targetSync:apply",

  // Plugins
  PLUGIN_LIBRARY_GET: "plugin:library:get",
  PLUGIN_LIBRARY_EXPORT_SNAPSHOT: "plugin:library:exportSnapshot",
  PLUGIN_LIBRARY_RESTORE_SNAPSHOT: "plugin:library:restoreSnapshot",
  PLUGIN_LIBRARY_EXPORT_FILES: "plugin:library:exportFiles",
  PLUGIN_LIBRARY_RESTORE_FILES: "plugin:library:restoreFiles",
  PLUGIN_MARKET_LIST: "plugin:market:list",
  PLUGIN_MARKET_SOURCES: "plugin:market:sources",
  PLUGIN_MARKET_PREVIEW: "plugin:market:preview",
  PLUGIN_MARKET_INSTALL: "plugin:market:install",
  PLUGIN_IMPORT_LOCAL: "plugin:import:local",
  PLUGIN_SOURCE_PREVIEW: "plugin:source:preview",
  PLUGIN_IMPORT_SOURCE: "plugin:import:source",
  PLUGIN_SOURCE_UPDATE_STATUS: "plugin:source:updateStatus",
  PLUGIN_SOURCE_UPDATE: "plugin:source:update",
  PLUGIN_UPDATE_METADATA: "plugin:updateMetadata",
  PLUGIN_DELETE: "plugin:delete",
  PLUGIN_EXPORT_MANIFEST: "plugin:exportManifest",
  PLUGIN_EXPORT_ZIP: "plugin:exportZip",
  PLUGIN_DISTRIBUTE: "plugin:distribute",
  PLUGIN_UNDISTRIBUTE: "plugin:undistribute",
  PLUGIN_IMPORT_CHILD_MCP: "plugin:import:childMcp",
  PLUGIN_PACKAGE_HEALTH_CHECK: "plugin:package:healthCheck",
  PLUGIN_VERSION_GET_ALL: "plugin:version:getAll",
  PLUGIN_VERSION_CREATE: "plugin:version:create",
  PLUGIN_VERSION_ROLLBACK: "plugin:version:rollback",
  PLUGIN_VERSION_DELETE: "plugin:version:delete",
  PLUGIN_TARGET_MATRIX: "plugin:target:matrix",

  // Data Recovery
  DATA_CHECK_RECOVERY: "data:checkRecovery",
  DATA_PREVIEW_RECOVERY: "data:previewRecovery",
  DATA_PERFORM_RECOVERY: "data:performRecovery",
  DATA_DISMISS_RECOVERY: "data:dismissRecovery",
  DATA_EXPORT_ZIP: "data:exportZip",
  DATA_PORTABLE_PREVIEW: "data:portablePreview",
  DATA_PORTABLE_RESTORE: "data:portableRestore",
  DATA_PORTABLE_LOGICAL_RESTORE: "data:portableLogicalRestore",
  UPGRADE_BACKUP_LIST: "upgradeBackup:list",
  UPGRADE_BACKUP_CREATE: "upgradeBackup:create",
  UPGRADE_BACKUP_RESTORE: "upgradeBackup:restore",
  UPGRADE_BACKUP_DELETE: "upgradeBackup:delete",

  // S3-compatible storage
  S3_TEST_CONNECTION: "s3:testConnection",
  S3_UPLOAD: "s3:upload",
  S3_DOWNLOAD: "s3:download",
  S3_STAT: "s3:stat",

  // Image
  DIALOG_SELECT_IMAGE: "dialog:selectImage",
  IMAGE_SAVE: "image:save",
  IMAGE_OPEN: "image:open",
  IMAGE_SAVE_BUFFER: "image:save-buffer",
  IMAGE_DOWNLOAD: "image:download",
  IMAGE_LIST: "image:list",
  IMAGE_GET_SIZE: "image:getSize",
  IMAGE_READ_BASE64: "image:readBase64",
  IMAGE_SAVE_BASE64: "image:saveBase64",
  IMAGE_EXISTS: "image:exists",
  IMAGE_CLEAR: "image:clear",

  // Video
  DIALOG_SELECT_VIDEO: "dialog:selectVideo",
  VIDEO_SAVE: "video:save",
  VIDEO_OPEN: "video:open",
  VIDEO_LIST: "video:list",
  VIDEO_GET_SIZE: "video:getSize",
  VIDEO_READ_BASE64: "video:readBase64",
  VIDEO_SAVE_BASE64: "video:saveBase64",
  VIDEO_EXISTS: "video:exists",
  VIDEO_GET_PATH: "video:getPath",
  VIDEO_CLEAR: "video:clear",
} as const;

export type IPCChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
