import type {
  RiskLayer,
  Surface,
  VerificationCheck,
  VerificationProfile,
} from "./types.mts";

const QUICK_PROFILES: VerificationProfile[] = [
  "changed",
  "quick",
  "release",
  "package",
];
const RELEASE_PROFILES: VerificationProfile[] = ["release", "package"];

function pnpmCheck(
  id: string,
  label: string,
  surfaces: Surface[],
  layers: RiskLayer[],
  args: string[],
  options: Partial<
    Pick<
      VerificationCheck,
      "profiles" | "dependsOn" | "timeoutMs" | "resourceGroup"
    >
  > & { environment?: Record<string, string> } = {},
): VerificationCheck {
  return {
    id,
    label,
    surfaces,
    layers,
    profiles: options.profiles ?? QUICK_PROFILES,
    command: { executable: "pnpm", args, environment: options.environment },
    dependsOn: options.dependsOn,
    timeoutMs: options.timeoutMs ?? 120_000,
    resourceGroup: options.resourceGroup,
  };
}

export const VERIFICATION_CHECKS: VerificationCheck[] = [
  pnpmCheck(
    "governance-ci-config",
    "CI surface selection tests",
    ["governance"],
    ["governance"],
    ["test:ci-config"],
  ),
  pnpmCheck(
    "governance-spec",
    "Specification governance",
    ["governance"],
    ["governance"],
    ["spec:test"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "governance-file-size",
    "Source file size limits",
    ["governance"],
    ["governance"],
    ["lint:file-size"],
  ),
  pnpmCheck(
    "shared-typecheck",
    "Shared package typecheck",
    ["shared"],
    ["static", "contract"],
    ["--filter", "@prompthub/shared", "typecheck"],
  ),
  pnpmCheck(
    "shared-test",
    "Shared package tests",
    ["shared"],
    ["unit", "contract"],
    ["--filter", "@prompthub/shared", "test"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "db-typecheck",
    "Database package typecheck",
    ["database"],
    ["static", "contract"],
    ["--filter", "@prompthub/db", "typecheck"],
  ),
  pnpmCheck(
    "core-typecheck",
    "Core package typecheck",
    ["core"],
    ["static", "contract"],
    ["--filter", "@prompthub/core", "typecheck"],
  ),
  pnpmCheck(
    "core-test",
    "Core package tests",
    ["core"],
    ["unit", "contract"],
    ["--filter", "@prompthub/core", "test"],
    { timeoutMs: 300_000, resourceGroup: "test-heavy" },
  ),
  pnpmCheck(
    "core-performance",
    "Core canonical storage performance budget",
    ["core"],
    ["performance"],
    ["--filter", "@prompthub/core", "test:performance"],
    {
      profiles: RELEASE_PROFILES,
      dependsOn: ["core-test"],
      timeoutMs: 120_000,
      resourceGroup: "test-heavy",
    },
  ),
  pnpmCheck(
    "cli-lint",
    "CLI lint",
    ["cli"],
    ["static"],
    ["--filter", "@prompthub/cli", "lint"],
  ),
  pnpmCheck(
    "cli-typecheck",
    "CLI typecheck",
    ["cli"],
    ["static", "contract"],
    ["--filter", "@prompthub/cli", "typecheck"],
  ),
  pnpmCheck(
    "cli-test",
    "CLI tests",
    ["cli"],
    ["unit", "contract", "security"],
    ["--filter", "@prompthub/cli", "test"],
    { timeoutMs: 180_000, resourceGroup: "test-heavy" },
  ),
  pnpmCheck(
    "cli-build",
    "CLI build",
    ["cli"],
    ["build"],
    ["--filter", "@prompthub/cli", "build"],
    { profiles: RELEASE_PROFILES, timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "cli-package",
    "CLI package proof",
    ["cli"],
    ["package"],
    ["--dir", "apps/cli", "pack", "--ignore-scripts"],
    {
      profiles: ["package"],
      dependsOn: ["cli-build"],
      timeoutMs: 180_000,
      resourceGroup: "package-artifact",
    },
  ),
  pnpmCheck(
    "desktop-lint",
    "Desktop lint",
    ["desktop"],
    ["static"],
    ["--filter", "@prompthub/desktop", "lint"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "desktop-typecheck",
    "Desktop typecheck",
    ["desktop"],
    ["static", "contract"],
    ["--filter", "@prompthub/desktop", "typecheck"],
    { timeoutMs: 360_000 },
  ),
  ...Array.from({ length: 8 }, (_, shard) =>
    pnpmCheck(
      `desktop-unit-${shard + 1}`,
      `Desktop unit tests (shard ${shard + 1}/8)`,
      ["desktop", "database"],
      ["unit", "contract", "security"],
      [
        "--filter",
        "@prompthub/desktop",
        "exec",
        "vitest",
        "run",
        "tests/unit",
        "--shard",
        `${shard + 1}/8`,
        "--minWorkers",
        "2",
        "--maxWorkers",
        "2",
      ],
      { timeoutMs: 600_000, resourceGroup: "test-heavy" },
    ),
  ),
  ...Array.from({ length: 4 }, (_, shard) =>
    pnpmCheck(
      `desktop-integration-${shard + 1}`,
      `Desktop integration tests (shard ${shard + 1}/4)`,
      ["desktop", "database"],
      ["integration", "contract"],
      [
        "--filter",
        "@prompthub/desktop",
        "exec",
        "vitest",
        "run",
        "tests/integration",
        "--shard",
        `${shard + 1}/4`,
        "--minWorkers",
        "1",
        "--maxWorkers",
        "1",
      ],
      {
        profiles: RELEASE_PROFILES,
        timeoutMs: 300_000,
        resourceGroup: "test-heavy",
      },
    ),
  ),
  pnpmCheck(
    "desktop-performance",
    "Desktop performance budget",
    ["desktop"],
    ["performance"],
    ["--filter", "@prompthub/desktop", "test:perf"],
    { profiles: RELEASE_PROFILES, timeoutMs: 300_000 },
  ),
  pnpmCheck(
    "desktop-build",
    "Desktop build",
    ["desktop"],
    ["build"],
    ["--filter", "@prompthub/desktop", "build"],
    {
      profiles: RELEASE_PROFILES,
      timeoutMs: 300_000,
      resourceGroup: "package-artifact",
    },
  ),
  pnpmCheck(
    "desktop-bundle-budget",
    "Desktop bundle budget",
    ["desktop"],
    ["performance"],
    ["--filter", "@prompthub/desktop", "bundle:budget"],
    {
      profiles: RELEASE_PROFILES,
      dependsOn: ["desktop-build"],
      timeoutMs: 120_000,
      resourceGroup: "package-artifact",
    },
  ),
  pnpmCheck(
    "desktop-e2e-smoke",
    "Desktop built-artifact E2E smoke",
    ["desktop"],
    ["e2e"],
    ["--filter", "@prompthub/desktop", "test:e2e:smoke:built"],
    {
      profiles: RELEASE_PROFILES,
      dependsOn: ["desktop-build"],
      timeoutMs: 600_000,
      resourceGroup: "electron-runtime",
    },
  ),
  pnpmCheck(
    "desktop-package",
    "Desktop package proof",
    ["desktop"],
    ["package"],
    ["--filter", "@prompthub/desktop", "electron:package:built"],
    {
      profiles: ["package"],
      dependsOn: ["desktop-build"],
      timeoutMs: 1_200_000,
      resourceGroup: "package-artifact",
    },
  ),
  pnpmCheck(
    "web-lint",
    "Self-hosted Web lint",
    ["web-self-hosted"],
    ["static"],
    ["--filter", "@prompthub/web", "lint"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "web-typecheck",
    "Self-hosted Web typecheck",
    ["web-self-hosted"],
    ["static", "contract"],
    ["--filter", "@prompthub/web", "typecheck"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "web-test",
    "Self-hosted Web tests",
    ["web-self-hosted", "database"],
    ["unit", "contract", "security"],
    ["--filter", "@prompthub/web", "test"],
    {
      timeoutMs: 360_000,
      resourceGroup: "test-heavy",
      environment: {
        JWT_SECRET: "test-secret-for-web-release-verification-1234567890",
      },
    },
  ),
  pnpmCheck(
    "web-build",
    "Self-hosted Web build",
    ["web-self-hosted"],
    ["build"],
    ["--filter", "@prompthub/web", "build"],
    {
      profiles: RELEASE_PROFILES,
      timeoutMs: 300_000,
      resourceGroup: "package-artifact",
    },
  ),
  pnpmCheck(
    "web-smoke",
    "Self-hosted Web smoke",
    ["web-self-hosted"],
    ["integration"],
    ["--filter", "@prompthub/web", "test:smoke"],
    {
      profiles: RELEASE_PROFILES,
      dependsOn: ["web-build"],
      timeoutMs: 180_000,
      resourceGroup: "network-port",
    },
  ),
  pnpmCheck(
    "web-cloudflare-lint",
    "Cloudflare Worker lint",
    ["web-cloudflare"],
    ["static"],
    ["--filter", "@prompthub/web-cloudflare", "lint"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "web-cloudflare-typecheck",
    "Cloudflare Worker typecheck",
    ["web-cloudflare"],
    ["static", "contract"],
    ["--filter", "@prompthub/web-cloudflare", "typecheck"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "web-cloudflare-test",
    "Cloudflare Worker tests",
    ["web-cloudflare"],
    ["unit", "contract", "security"],
    ["--filter", "@prompthub/web-cloudflare", "test"],
    { timeoutMs: 300_000, resourceGroup: "test-heavy" },
  ),
  pnpmCheck(
    "web-cloudflare-build",
    "Cloudflare Worker dry-run build",
    ["web-cloudflare"],
    ["build"],
    [
      "--filter",
      "@prompthub/web-cloudflare",
      "exec",
      "wrangler",
      "deploy",
      "--dry-run",
      "--outdir",
      "dist",
    ],
    {
      profiles: RELEASE_PROFILES,
      timeoutMs: 300_000,
      resourceGroup: "package-artifact",
      environment: {
        CI: "true",
        WRANGLER_SEND_METRICS: "false",
      },
    },
  ),
  pnpmCheck(
    "mobile-typecheck",
    "Mobile typecheck",
    ["mobile"],
    ["static", "contract"],
    ["--filter", "@prompthub/mobile", "typecheck"],
    { timeoutMs: 180_000 },
  ),
  pnpmCheck(
    "mobile-test",
    "Mobile tests",
    ["mobile"],
    ["unit", "contract"],
    ["--filter", "@prompthub/mobile", "test"],
    { timeoutMs: 180_000 },
  ),
];
